global:
  resolve_timeout: 5m

route:
  receiver: telephony-default
  group_by:
    - alertname
    - severity
    - team
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - team="telephony"
        - severity="critical"
      receiver: telephony-critical
      continue: false
    - matchers:
        - team="telephony"
        - severity="warning"
      receiver: telephony-warning
      continue: false

inhibit_rules:
  - source_matchers:
      - team="telephony"
      - severity="critical"
    target_matchers:
      - team="telephony"
      - severity="warning"
    equal:
      - alertname

receivers:
  - name: telephony-default
  - name: telephony-critical
  - name: telephony-warning
