#!/bin/bash
# Run this ONCE on the production server to write /opt/talky/backend/.env
# with all the values needed for the backend to boot. After this runs you
# can edit the .env directly to tweak values, but you should not need to.
#
# This script:
#   - Generates fresh JWT_SECRET, SECRET_KEY, CONNECTOR_ENCRYPTION_KEY
#     (production must NOT reuse dev secrets)
#   - Reads DB / Redis passwords from /opt/talky/secrets/
#   - Hard-codes the AI provider API keys (Deepgram, Groq, Google TTS,
#     Gemini, ElevenLabs, Cartesia, Google OAuth)
#   - Hard-codes the Microsoft 365 SMTP creds for the noreply mailbox
#   - Sets FRONTEND_URL / API_BASE_URL to placeholders — you MUST edit
#     them before starting the API
#
# Run with:   bash /opt/talky/setup-backend-env.sh
set -e

cd /opt/talky

# Sanity: required input files
[ -f secrets/db-password ] || { echo "ERROR: secrets/db-password missing"; exit 1; }
[ -f secrets/redis-password ] || { echo "ERROR: secrets/redis-password missing"; exit 1; }

DB_PASS=$(cat secrets/db-password)
REDIS_PASS=$(cat secrets/redis-password)

# Generate fresh production secrets if they don't already exist
if [ ! -f secrets/jwt-secret ]; then
    openssl rand -base64 64 | tr -d '\n=+/' | head -c 64 > secrets/jwt-secret
    chmod 600 secrets/jwt-secret
fi
if [ ! -f secrets/app-secret-key ]; then
    openssl rand -base64 64 | tr -d '\n=+/' | head -c 64 > secrets/app-secret-key
    chmod 600 secrets/app-secret-key
fi
if [ ! -f secrets/connector-encryption-key ]; then
    # CONNECTOR_ENCRYPTION_KEY must be a 32-byte url-safe-base64 Fernet key
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" \
        > secrets/connector-encryption-key 2>/dev/null \
        || openssl rand -base64 32 > secrets/connector-encryption-key
    chmod 600 secrets/connector-encryption-key
fi

JWT_SECRET=$(cat secrets/jwt-secret)
APP_SECRET=$(cat secrets/app-secret-key)
CONN_KEY=$(cat secrets/connector-encryption-key)

# Find the GCP service-account JSON that came over via rsync
GCP_JSON=$(ls /opt/talky/backend/gen-lang-client-*.json 2>/dev/null | head -1)
if [ -z "$GCP_JSON" ]; then
    echo "WARNING: GCP service-account JSON not found in backend/. Google TTS will not work."
    GCP_JSON="/opt/talky/backend/gen-lang-client-MISSING.json"
fi

# Write the .env. Each line is a complete env var assignment.
ENV_PATH=/opt/talky/backend/.env
> "$ENV_PATH"   # truncate

cat <<KEYS >> "$ENV_PATH"
# ─────────────────────────────────────────────────────────
# Talky.ai backend environment — production server
# Generated by setup-backend-env.sh
# ─────────────────────────────────────────────────────────
ENVIRONMENT=production

# Postgres / Redis (passwords from /opt/talky/secrets/)
DATABASE_URL=postgresql://talkyai:${DB_PASS}@127.0.0.1:5432/talkyai
REDIS_URL=redis://:${REDIS_PASS}@127.0.0.1:6379

# Auth secrets (fresh production values, NOT from dev)
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY_HOURS=24
SECRET_KEY=${APP_SECRET}
CONNECTOR_ENCRYPTION_KEY=${CONN_KEY}

# STT / TTS / LLM API keys — placeholders. Real values live in
# /opt/talky/secrets/ai-keys.env and are sourced after this script runs.
# See setup-backend-env-secrets.md for the expected file layout.
DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-REPLACE_ME}
ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY:-REPLACE_ME}
CARTESIA_API_KEY=${CARTESIA_API_KEY:-REPLACE_ME}
GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY:-REPLACE_ME}
GOOGLE_APPLICATION_CREDENTIALS=${GCP_JSON}
GROQ_API_KEY=${GROQ_API_KEY:-REPLACE_ME}
GEMINI_API_KEY=${GEMINI_API_KEY:-REPLACE_ME}

# Google OAuth (Gmail / Calendar / Drive connectors)
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-REPLACE_ME}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-REPLACE_ME}

# URLs — EDIT THESE BEFORE STARTING THE API
# Replace YOUR-DOMAIN.com with the real domain you've pointed at this server.
FRONTEND_URL=https://app.YOUR-DOMAIN.com
API_BASE_URL=https://api.YOUR-DOMAIN.com

# Asterisk ARI — local Asterisk to be installed in Phase 7
ASTERISK_ARI_HOST=127.0.0.1
ASTERISK_ARI_PORT=8088
ASTERISK_ARI_USER=talky
ASTERISK_ARI_PASSWORD=talky_local_only_change_me
ASTERISK_ARI_APP=talky_ai
ASTERISK_GATEWAY_BASE_URL=http://127.0.0.1:18080
ASTERISK_GATEWAY_RTP_IP=127.0.0.1
ASTERISK_RTP_PORT_START=32000
ASTERISK_RTP_PORT_END=32999
BACKEND_INTERNAL_URL=http://127.0.0.1:8000

# Microsoft 365 SMTP (noreply mailbox)
SMTP_HOST=smtp.office365.com
SMTP_PORT=587
SMTP_USER=noreply@talkleeai.com
SMTP_PASSWORD=${SMTP_PASSWORD:-REPLACE_ME}
SMTP_FROM_EMAIL=noreply@talkleeai.com
SMTP_FROM_NAME=Talky.ai
SMTP_USE_TLS=true
EMAIL_USER=noreply@talkleeai.com
EMAIL_PASS=${SMTP_PASSWORD:-REPLACE_ME}
KEYS

chmod 600 "$ENV_PATH"

echo "==> Wrote $ENV_PATH"
echo "==> Contents (values redacted):"
sed 's/=.*/=***/' "$ENV_PATH" | grep -v '^#' | grep -v '^$'
echo
echo "==> Fresh production secrets generated and saved to /opt/talky/secrets/"
ls -la /opt/talky/secrets/
echo
echo "==> NEXT: edit /opt/talky/backend/.env and replace YOUR-DOMAIN.com on"
echo "    FRONTEND_URL and API_BASE_URL with your actual domain. Then we can"
echo "    move to Phase 5 (boot the API)."
