{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "talky.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "talky.labels" . | nindent 4 }}
{{- end -}}
