apiVersion: v1
kind: Service
metadata:
  name: {{ include "talky.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "talky.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  selector: {{- include "talky.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
