#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TELEPHONY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$TELEPHONY_ROOT/deploy/docker/docker-compose.telephony.yml"
ENV_FILE="${1:-$TELEPHONY_ROOT/deploy/docker/.env.telephony}"
DOC_ROOT="$TELEPHONY_ROOT/docs/phase_3"
EVIDENCE_DIR="$DOC_ROOT/evidence/day2"
mkdir -p "$EVIDENCE_DIR"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[ERROR] Missing env file: $ENV_FILE"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

compose_cmd=(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE")
ASTERISK_PORT="${ASTERISK_SIP_PORT:-5070}"

CALL_JSON="$EVIDENCE_DIR/day2_call_summary.json"
SIP_LOG="$EVIDENCE_DIR/day2_asterisk_sip_log_excerpt.log"
EVIDENCE_DOC="$DOC_ROOT/day2_asterisk_call_evidence.md"
RUNBOOK_DOC="$DOC_ROOT/runbook_asterisk.md"

echo "[1/7] Ensuring Day 2 baseline container is running..."
if ! docker ps --format '{{.Names}}' | grep -qx "talky-asterisk"; then
  "${compose_cmd[@]}" up -d --no-recreate asterisk
  sleep 6
fi

echo "[2/7] Verifying Asterisk control access..."
"${compose_cmd[@]}" exec -T asterisk asterisk -rx "core show uptime seconds" >/dev/null
"${compose_cmd[@]}" exec -T asterisk asterisk -rx "pjsip show transports" | grep -q "${ASTERISK_PORT}"

echo "[3/7] Preparing SIP logging..."
"${compose_cmd[@]}" exec -T asterisk asterisk -rx "pjsip set logger on" >/dev/null
start_ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "[4/7] Running 10 SIP call probes to Asterisk..."
python3 "$SCRIPT_DIR/sip_invite_call_probe.py" \
  --host 127.0.0.1 \
  --port "$ASTERISK_PORT" \
  --extension 700 \
  --calls 10 \
  --bind-ip 127.0.0.1 \
  --timeout 4.0 \
  --hold-ms 150 \
  --evidence-file "$CALL_JSON"

echo "[5/7] Capturing SIP logs for INVITE -> 200 OK -> BYE proof..."
"${compose_cmd[@]}" exec -T asterisk sh -lc "sleep 1" >/dev/null
docker logs --since "$start_ts" talky-asterisk >"$SIP_LOG" 2>&1 || true
"${compose_cmd[@]}" exec -T asterisk asterisk -rx "pjsip set logger off" >/dev/null || true

invite_count="$(grep -c "INVITE sip:" "$SIP_LOG" || true)"
bye_count="$(grep -c "BYE sip:" "$SIP_LOG" || true)"
ok_count="$(grep -c "SIP/2.0 200 OK" "$SIP_LOG" || true)"

if [[ "$invite_count" -lt 10 ]]; then
  echo "[ERROR] Expected >=10 INVITE entries in Asterisk SIP logs, got $invite_count"
  exit 1
fi
if [[ "$bye_count" -lt 10 ]]; then
  echo "[ERROR] Expected >=10 BYE entries in Asterisk SIP logs, got $bye_count"
  exit 1
fi
if [[ "$ok_count" -lt 10 ]]; then
  echo "[ERROR] Expected >=10 SIP/2.0 200 OK entries in Asterisk SIP logs, got $ok_count"
  exit 1
fi

echo "[6/7] Rendering Day 2 runbook/evidence docs..."
cat >"$RUNBOOK_DOC" <<'EOF'
# Runbook: Day 2 Asterisk First Call Validation

## Objective

Validate baseline Asterisk call flow for extension `700` with repeated call setup and teardown.

## Command

```bash
bash telephony/scripts/verify_day2_asterisk_first_call.sh telephony/deploy/docker/.env.telephony.example
```

## What It Verifies

1. Asterisk is listening on configured internal SIP port (`ASTERISK_SIP_PORT`, frozen default `5070`).
2. Ten SIP INVITE calls to extension `700` complete with BYE.
3. Asterisk SIP logs contain the expected sequence markers:
   - `INVITE sip:`
   - `SIP/2.0 200 OK`
   - `BYE sip:`

## Evidence Files

1. `telephony/docs/phase_3/evidence/day2/day2_call_summary.json`
2. `telephony/docs/phase_3/evidence/day2/day2_asterisk_sip_log_excerpt.log`

EOF

cat >"$EVIDENCE_DOC" <<EOF
# Day 2 Asterisk First Call Evidence

Generated by: \`telephony/scripts/verify_day2_asterisk_first_call.sh\`

## Acceptance Status

1. 10 calls connected and hung up cleanly: PASS
2. Asterisk logs show INVITE -> 200 OK -> BYE markers: PASS

## Counts

1. INVITE count: ${invite_count}
2. BYE count: ${bye_count}
3. SIP/2.0 200 OK count: ${ok_count}

## Evidence

1. \`telephony/docs/phase_3/evidence/day2/day2_call_summary.json\`
2. \`telephony/docs/phase_3/evidence/day2/day2_asterisk_sip_log_excerpt.log\`

EOF

echo "[7/7] Day 2 verification complete."
echo "Day 2 verification PASSED."
