#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TELEPHONY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$TELEPHONY_ROOT/deploy/docker/docker-compose.telephony.yml"
ENV_FILE="${1:-$TELEPHONY_ROOT/deploy/docker/.env.telephony}"
DOC_ROOT="$TELEPHONY_ROOT/docs/phase_3"
EVIDENCE_DIR="$DOC_ROOT/evidence/day3"
mkdir -p "$EVIDENCE_DIR"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[ERROR] Missing env file: $ENV_FILE"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

compose_cmd=(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE")
SIP_PORT="${OPENSIPS_SIP_PORT:-15060}"
ASTERISK_PORT="${ASTERISK_SIP_PORT:-5070}"

OPEN_SUCCESS_JSON="$EVIDENCE_DIR/day3_opensips_success_calls.json"
DIRECT_BLOCK_JSON="$EVIDENCE_DIR/day3_direct_asterisk_blocked.json"
EVIDENCE_DOC="$DOC_ROOT/day3_opensips_edge_evidence.md"

echo "[1/8] Ensuring OpenSIPS + Asterisk + RTPengine containers are running..."
for cname in talky-asterisk talky-rtpengine talky-opensips; do
  if ! docker ps --format '{{.Names}}' | grep -qx "$cname"; then
    "${compose_cmd[@]}" up -d --no-recreate asterisk rtpengine opensips
    sleep 8
    break
  fi
done

echo "[2/8] Verifying OpenSIPS routes to Asterisk internal port ${ASTERISK_PORT}..."
if ! grep -Fq "sip:\$rU@127.0.0.1:${ASTERISK_PORT}" "$TELEPHONY_ROOT/opensips/conf/opensips.cfg"; then
  echo "[ERROR] OpenSIPS route target is not set to Asterisk port ${ASTERISK_PORT}"
  exit 1
fi

echo "[3/8] Verifying Asterisk source match policy exists..."
if ! grep -Fq "match=127.0.0.1" "$TELEPHONY_ROOT/asterisk/conf/pjsip.conf"; then
  echo "[ERROR] Asterisk source-match ACL for OpenSIPS loopback not found."
  exit 1
fi

echo "[4/8] Running success calls through OpenSIPS edge..."
python3 "$SCRIPT_DIR/sip_invite_call_probe.py" \
  --host 127.0.0.1 \
  --port "$SIP_PORT" \
  --extension 700 \
  --calls 5 \
  --bind-ip 127.0.0.1 \
  --timeout 4.0 \
  --hold-ms 120 \
  --evidence-file "$OPEN_SUCCESS_JSON"

echo "[5/8] Detecting non-loopback source IP for direct-block check..."
bind_ip="$(python3 - <<'PY'
import socket
ip = "127.0.0.1"
try:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("1.1.1.1", 80))
    ip = s.getsockname()[0]
    s.close()
except OSError:
    pass
print(ip)
PY
)"

if [[ "$bind_ip" == "127.0.0.1" ]]; then
  echo "[ERROR] Could not detect non-loopback IPv4 for direct-block test."
  exit 1
fi

echo "[6/8] Verifying direct call path to Asterisk is blocked for non-OpenSIPS source (${bind_ip})..."
python3 "$SCRIPT_DIR/sip_invite_call_probe.py" \
  --host "$bind_ip" \
  --port "$ASTERISK_PORT" \
  --extension 700 \
  --calls 1 \
  --bind-ip "$bind_ip" \
  --timeout 3.0 \
  --expect-blocked \
  --evidence-file "$DIRECT_BLOCK_JSON"

echo "[7/8] Rendering Day 3 evidence doc..."
cat >"$EVIDENCE_DOC" <<EOF
# Day 3 OpenSIPS Edge Enforcement Evidence

Generated by: \`telephony/scripts/verify_day3_opensips_edge.sh\`

## Acceptance Status

1. Calls succeed through OpenSIPS edge: PASS
2. Direct call path to Asterisk from non-OpenSIPS source: BLOCKED (PASS)

## Config Assertions

1. OpenSIPS route target: \`sip:\$rU@127.0.0.1:${ASTERISK_PORT}\`
2. Asterisk identify ACL marker: \`match=127.0.0.1\`

## Evidence Files

1. \`telephony/docs/phase_3/evidence/day3/day3_opensips_success_calls.json\`
2. \`telephony/docs/phase_3/evidence/day3/day3_direct_asterisk_blocked.json\`

EOF

echo "[8/8] Day 3 verification complete."
echo "Day 3 verification PASSED."
