#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TELEPHONY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOC_ROOT="$TELEPHONY_ROOT/docs/phase_3"
EVIDENCE_DIR="$DOC_ROOT/evidence/day1"
mkdir -p "$EVIDENCE_DIR"

INVENTORY_DOC="$DOC_ROOT/inventory.md"
UFW_DOC="$DOC_ROOT/ufw_status.md"
TOOLS_EVIDENCE="$EVIDENCE_DIR/day1_tools_check.txt"
NETWORK_EVIDENCE="$EVIDENCE_DIR/day1_network_check.txt"
UFW_EVIDENCE="$EVIDENCE_DIR/day1_ufw_raw.txt"

echo "[1/5] Collecting host/network inventory evidence..."
{
  echo "timestamp_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "hostname=$(hostname)"
  echo "ipv4_addresses="
  ip -4 addr show | sed -n 's/^[[:space:]]*inet[[:space:]]\([^ ]*\).*/\1/p'
  echo "default_route="
  ip route show default || true
} >"$NETWORK_EVIDENCE"

echo "[2/5] Checking required LAN diagnostic tools..."
{
  for cmd in sngrep tcpdump iftop htop; do
    if command -v "$cmd" >/dev/null 2>&1; then
      echo "$cmd=installed ($(command -v "$cmd"))"
    else
      echo "$cmd=missing"
    fi
  done
} >"$TOOLS_EVIDENCE"

echo "[3/5] Running baseline reachability checks..."
ping -c 1 127.0.0.1 >/dev/null
if command -v ssh >/dev/null 2>&1; then
  ssh -o BatchMode=yes -o ConnectTimeout=2 localhost true >/dev/null 2>&1 || true
fi

echo "[4/5] Capturing firewall posture..."
{
  echo "timestamp_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    echo "command=ufw status verbose"
    if ufw status verbose; then
      echo "status_capture=ok"
    else
      echo "status_capture=ufw_command_failed"
    fi
  else
    echo "command=sudo -n ufw status verbose"
    if sudo -n ufw status verbose; then
      echo "status_capture=ok"
    else
      echo "status_capture=needs_root_or_manual"
      echo "fallback_command=ufw status verbose"
      ufw status verbose 2>&1 || true
    fi
  fi
} >"$UFW_EVIDENCE"

echo "[5/5] Rendering Day 1 docs..."
cat >"$INVENTORY_DOC" <<'EOF'
# Day 1 Inventory (LAN Setup)

Generated by: `telephony/scripts/verify_day1_lan_setup.sh`  
Source evidence:
1. `telephony/docs/phase_3/evidence/day1/day1_network_check.txt`
2. `telephony/docs/phase_3/evidence/day1/day1_tools_check.txt`

## Host Inventory

Current node details are captured in:
1. `telephony/docs/phase_3/evidence/day1/day1_network_check.txt`

## Required Ports (Frozen Plan Baseline)

1. OpenSIPS SIP UDP/TCP: `15060`
2. OpenSIPS SIP TLS: `15061`
3. Asterisk PJSIP internal: `5070`
4. RTPengine NG control: `2223`
5. RTP media range: `30000-34999`

## LAN Readiness Checklist

1. Static IP and hostname documented.
2. Required diagnostic tools checked (`sngrep`, `tcpdump`, `iftop`, `htop`).
3. Reachability baseline executed (`ping 127.0.0.1`).
4. SSH local key-mode check attempted (best effort).

EOF

cat >"$UFW_DOC" <<'EOF'
# Day 1 Firewall Posture (UFW)

Generated by: `telephony/scripts/verify_day1_lan_setup.sh`  
Raw evidence:
1. `telephony/docs/phase_3/evidence/day1/day1_ufw_raw.txt`

## Notes

1. If this environment does not allow passwordless sudo, UFW output may show a root-permission requirement.
2. Final acceptance on a target LAN node should execute:
   - `sudo ufw status verbose`
3. The captured output still records the exact command and current permission state.

EOF

echo
echo "Day 1 verification artifacts generated."
echo "inventory doc: $INVENTORY_DOC"
echo "ufw doc:       $UFW_DOC"
