"""add stream_events table for the user-facing Event Stream panel

The Event Stream on the campaigns page used to render client-side mock
events generated by `setInterval(generateEvent, 9000)`. This migration
adds the persistent backing store for real events emitted by the
campaigns endpoints, the dialer worker, and the telephony rate limiter.

Separate from `audit_logs` so the tamper-evident compliance chain
doesn't get polluted with high-volume user-facing notifications.
Different retention (90 days) and access pattern (tenant-scoped reads,
indexed by recency) than audit_logs.

Revision ID: 0003_add_stream_events
Revises: 0002_add_refresh_tokens
Create Date: 2026-05-14 00:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
from sqlalchemy import text

revision: str = "0003_add_stream_events"
down_revision: Union[str, None] = "0002_add_refresh_tokens"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(text("""
        CREATE TABLE IF NOT EXISTS stream_events (
            id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
            tenant_id           UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
            category            TEXT        NOT NULL
                                CHECK (category IN
                                       ('campaign','system','alert','user_action','milestone')),
            title               TEXT        NOT NULL,
            description         TEXT,
            severity            TEXT        CHECK (severity IS NULL OR severity IN
                                                   ('info','warning','critical')),
            related_campaign_id UUID,
            related_call_id     UUID,
            actor_user_id       UUID,
            metadata            JSONB,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            expires_at          TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '90 days')
        )
    """))

    op.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_se_tenant_recent "
        "ON stream_events (tenant_id, created_at DESC)"
    ))
    op.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_se_tenant_category "
        "ON stream_events (tenant_id, category, created_at DESC)"
    ))
    op.execute(text(
        "CREATE INDEX IF NOT EXISTS idx_se_expires "
        "ON stream_events (expires_at)"
    ))

    op.execute(text("ALTER TABLE stream_events ENABLE ROW LEVEL SECURITY"))
    op.execute(text("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies
                WHERE tablename = 'stream_events'
                AND policyname = 'stream_events_tenant_isolation'
            ) THEN
                CREATE POLICY stream_events_tenant_isolation ON stream_events
                USING (tenant_id::text = current_setting('app.current_tenant_id', true));
            END IF;
        END $$
    """))


def downgrade() -> None:
    op.execute(text("DROP TABLE IF EXISTS stream_events CASCADE"))
