"""
app/core/kms.py — Key Management Service abstraction for SecretsManager

Replaces the XOR-based _encrypt_dek / _decrypt_dek placeholder in
secrets_manager.py with real hardware-backed key wrapping.

Supported backends (selected via KMS_PROVIDER env var):
  aws     — AWS KMS (production recommended)
  local   — AES-256-GCM wrap using SECRETS_MASTER_KEY env var (dev/test only)

Usage in secrets_manager.py:
    from app.core.kms import get_kms_backend
    _kms = get_kms_backend()

    # Replace:  self._encrypt_dek(dek)
    # With:     await _kms.wrap_key(dek)

    # Replace:  self._decrypt_dek(encrypted_dek)
    # With:     await _kms.unwrap_key(encrypted_dek)

Environment variables:
  KMS_PROVIDER          = aws | local (default: local)
  KMS_KEY_ID            = arn:aws:kms:us-east-1:123456789:key/abc...  (AWS only)
  KMS_REGION            = us-east-1 (AWS only)
  SECRETS_MASTER_KEY    = hex-encoded 32-byte key (local backend only)
                          Generate: python3 -c "import secrets; print(secrets.token_hex(32))"
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os
import secrets
from abc import ABC, abstractmethod
from typing import Optional

logger = logging.getLogger(__name__)

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    _CRYPTO_AVAILABLE = True
except ImportError:
    _CRYPTO_AVAILABLE = False

try:
    import boto3
    from botocore.exceptions import ClientError
    _BOTO3_AVAILABLE = True
except ImportError:
    _BOTO3_AVAILABLE = False


# ---------------------------------------------------------------------------
# Abstract interface
# ---------------------------------------------------------------------------

class KMSBackend(ABC):
    """
    Minimal interface for wrapping/unwrapping Data Encryption Keys (DEKs).

    The KMS backend never sees plaintext secret data — only DEKs (random
    32-byte AES keys). The DEK encrypts the actual secret value using
    AES-256-GCM in secrets_manager.py.
    """

    @abstractmethod
    async def wrap_key(self, plaintext_dek: bytes) -> bytes:
        """
        Wrap (encrypt) a DEK using the master key in the KMS.
        Returns the wrapped (ciphertext) DEK for storage in the database.
        """

    @abstractmethod
    async def unwrap_key(self, wrapped_dek: bytes) -> bytes:
        """
        Unwrap (decrypt) a wrapped DEK.
        Returns the plaintext DEK for in-memory use during decryption.
        """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Human-readable provider name for logging."""


# ---------------------------------------------------------------------------
# AWS KMS backend
# ---------------------------------------------------------------------------

class AWSKMSBackend(KMSBackend):
    """
    Wraps/unwraps DEKs using AWS KMS GenerateDataKey / Decrypt API.

    The KMS key ID (CMK) never leaves AWS — only the encrypted DEK
    is stored in the database. Even if the database is compromised,
    an attacker cannot decrypt secrets without AWS KMS access.

    IAM policy required:
      kms:GenerateDataKey
      kms:Decrypt
    """

    def __init__(self, key_id: str, region: str = "us-east-1") -> None:
        if not _BOTO3_AVAILABLE:
            raise RuntimeError(
                "boto3 is required for AWS KMS backend. "
                "Install with: pip install boto3"
            )
        self._key_id = key_id
        self._client = boto3.client("kms", region_name=region)
        logger.info(f"AWS KMS backend initialised (key_id={key_id[:20]}...)")

    @property
    def provider_name(self) -> str:
        return "aws_kms"

    async def wrap_key(self, plaintext_dek: bytes) -> bytes:
        """
        Use AWS KMS Encrypt to wrap the DEK.

        We use kms.encrypt() (not GenerateDataKey) because the DEK is
        already generated by secrets_manager._generate_dek(). The DEK
        is 32 bytes — well within the KMS 4096-byte plaintext limit.
        """
        try:
            response = self._client.encrypt(
                KeyId=self._key_id,
                Plaintext=plaintext_dek,
                EncryptionContext={"service": "talky-secrets-manager"},
            )
            return response["CiphertextBlob"]
        except ClientError as exc:
            logger.error(f"AWS KMS encrypt failed: {exc}")
            raise RuntimeError(f"KMS key wrapping failed: {exc}") from exc

    async def unwrap_key(self, wrapped_dek: bytes) -> bytes:
        """Use AWS KMS Decrypt to unwrap the DEK."""
        try:
            response = self._client.decrypt(
                CiphertextBlob=wrapped_dek,
                KeyId=self._key_id,
                EncryptionContext={"service": "talky-secrets-manager"},
            )
            return response["Plaintext"]
        except ClientError as exc:
            logger.error(f"AWS KMS decrypt failed: {exc}")
            raise RuntimeError(f"KMS key unwrapping failed: {exc}") from exc


# ---------------------------------------------------------------------------
# Local AES-GCM backend (development / single-server)
# ---------------------------------------------------------------------------

class LocalKMSBackend(KMSBackend):
    """
    Wraps DEKs using AES-256-GCM with a master key from the environment.

    Suitable for:
      - Local development
      - Single-server deployments where AWS KMS is not available

    NOT suitable for:
      - Multi-region deployments (key rotation is manual)
      - High-security requirements (key material lives in an env var)

    The master key MUST be set in SECRETS_MASTER_KEY (64-char hex).
    If not set, a random key is generated at startup — this means all
    previously encrypted DEKs become permanently unreadable after restart.
    """

    def __init__(self, master_key: Optional[bytes] = None) -> None:
        if not _CRYPTO_AVAILABLE:
            raise RuntimeError(
                "cryptography package required. Install: pip install cryptography"
            )

        if master_key:
            self._kek = master_key
        else:
            env_key = os.getenv("SECRETS_MASTER_KEY", "")
            if env_key:
                try:
                    self._kek = bytes.fromhex(env_key)
                except ValueError:
                    # Try base64 in case the user base64-encoded it
                    self._kek = base64.b64decode(env_key)
            else:
                self._kek = secrets.token_bytes(32)
                logger.warning(
                    "SECRETS_MASTER_KEY not set — generated ephemeral key. "
                    "All secrets will be UNREADABLE after restart. "
                    "Set SECRETS_MASTER_KEY in your .env file."
                )

        if len(self._kek) not in (16, 24, 32):
            raise ValueError(
                f"SECRETS_MASTER_KEY must be 16, 24, or 32 bytes "
                f"(got {len(self._kek)} bytes)"
            )

        # Derive a stable wrapping key from the master key using HKDF-like expansion
        self._wrap_key = hashlib.sha256(b"talky-dek-wrap-v1:" + self._kek).digest()
        logger.info("Local AES-GCM KMS backend initialised")

    @property
    def provider_name(self) -> str:
        return "local_aes_gcm"

    async def wrap_key(self, plaintext_dek: bytes) -> bytes:
        """Encrypt DEK with AES-256-GCM using the derived wrapping key."""
        aesgcm = AESGCM(self._wrap_key)
        iv = os.urandom(12)  # 96-bit nonce
        ciphertext = aesgcm.encrypt(iv, plaintext_dek, b"dek-wrap")
        # Store iv + ciphertext together (iv is 12 bytes, always)
        return iv + ciphertext

    async def unwrap_key(self, wrapped_dek: bytes) -> bytes:
        """Decrypt a wrapped DEK."""
        if len(wrapped_dek) < 12:
            raise ValueError("Wrapped DEK too short — possibly corrupted")
        iv, ciphertext = wrapped_dek[:12], wrapped_dek[12:]
        aesgcm = AESGCM(self._wrap_key)
        try:
            return aesgcm.decrypt(iv, ciphertext, b"dek-wrap")
        except Exception as exc:
            raise RuntimeError("DEK unwrap failed — wrong master key?") from exc


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

_backend: Optional[KMSBackend] = None


def get_kms_backend() -> KMSBackend:
    """
    Return the configured KMS backend (singleton).

    Selection:
      KMS_PROVIDER=aws   → AWSKMSBackend  (requires KMS_KEY_ID)
      KMS_PROVIDER=local → LocalKMSBackend (default)
    """
    global _backend
    if _backend is not None:
        return _backend

    provider = os.getenv("KMS_PROVIDER", "local").lower().strip()

    if provider == "aws":
        key_id = os.getenv("KMS_KEY_ID")
        if not key_id:
            raise RuntimeError(
                "KMS_KEY_ID must be set when KMS_PROVIDER=aws. "
                "Example: arn:aws:kms:us-east-1:123456789012:key/abc-def"
            )
        region = os.getenv("KMS_REGION", "us-east-1")
        _backend = AWSKMSBackend(key_id=key_id, region=region)

    elif provider == "local":
        _backend = LocalKMSBackend()

    else:
        raise ValueError(
            f"Unknown KMS_PROVIDER '{provider}'. "
            "Supported values: aws, local"
        )

    logger.info(f"KMS backend: {_backend.provider_name}")
    return _backend
